### ISSUE TITLE
Ring not closed in a readme examples

### ISSUE THREAD

**Issue by zartek** [zachcp/chemdoodle#3]
Hi,

Examples:
library(chemdoodle)
chemdoodle_viewer("C1CCCCC")
chemdoodle_transform("C1CCCCC")

Error:
Error in .jcall(parser, "Lorg/openscience/cdk/interfaces/IAtomContainer;",  : 
  org.openscience.cdk.exception.InvalidSmilesException: could not parse 'C1CCCCC', Unclosed ring detected:
C1CCCCC

This works: chemdoodle_viewer("C1CCCCC1")

Cheers

**Comment by zachcp** [comment]
thank @zartek. I closed the SMILES rings

**Comment by chengqian-lu** [comment]
Could you tell me how to close the SMILES rings please? As an example, drug DB05428, its SMILES is "[Gd+3].CC([O-])=O.CC([O-])=O.CCC1=C(CC)/C2=C/C3=N/C(=C\N=C4/C=C(OCCOCCOCCOC)C(OCCOCCOCCOC)=C/C/4=N\C=C4/N=C(/C=C\1\[N-]\2)C(CCCO)=C4C)/C(C)=C3CCCO"
